#!/bin/bash

# ./analyse_replicate.sh analysis_results LUNG_CANCER LET-1 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LET-1/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LET-1 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LET-1/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LET-1 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LET-1/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LET-1 bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LET-1/bio_1/tech_4/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/LUNG_CANCER/LET-1/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LET-1/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LET-1/bio_1/tech_3/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LET-1/bio_1/tech_4/summarized_info_of_unique_17_count.csv normalized_count,avg_count_per_number_of_barcodes,count avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv
# python pyscripts/normalize_column_by_factor.py analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv 4 normalized_count,avg_count_per_number_of_barcodes,count 1 analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC/bio_1/tech_4/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/LUNG_CANCER/LLC/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC/bio_1/tech_3/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC/bio_1/tech_4/summarized_info_of_unique_17_count.csv normalized_count,avg_count_per_number_of_barcodes,count avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/LLC/bio_1/summarized_info_of_unique_17_count.csv
# python pyscripts/normalize_column_by_factor.py analysis_results/LUNG_CANCER/LLC/bio_1/summarized_info_of_unique_17_count.csv 4 normalized_count,avg_count_per_number_of_barcodes,count 1 analysis_results/LUNG_CANCER/LLC/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC_2 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC_2/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC_2 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC_2/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER LLC_2 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/LLC_2/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/LUNG_CANCER/LLC_2/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC_2/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC_2/bio_1/tech_3/summarized_info_of_unique_17_count.csv normalized_count,avg_count_per_number_of_barcodes,count avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv
# python pyscripts/normalize_column_by_factor.py analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv 3 normalized_count,avg_count_per_number_of_barcodes,count 1 analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results LUNG_CANCER nMuMG bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/nMuMG/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER nMuMG bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/nMuMG/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER nMuMG bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/nMuMG/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER nMuMG bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/nMuMG/bio_1/tech_4/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/LUNG_CANCER/nMuMG/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/tech_3/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/tech_4/summarized_info_of_unique_17_count.csv normalized_count,avg_count_per_number_of_barcodes,count avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv
# python pyscripts/normalize_column_by_factor.py analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv 4 normalized_count,avg_count_per_number_of_barcodes,count 1 analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results LUNG_CANCER MEF bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/MEF/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER MEF bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/MEF/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER MEF bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/MEF/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results LUNG_CANCER MEF bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/LUNG_CANCER/MEF/bio_1/tech_4/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/LUNG_CANCER/MEF/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/tech_3/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/tech_4/summarized_info_of_unique_17_count.csv normalized_count,avg_count_per_number_of_barcodes,count avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv
# python pyscripts/normalize_column_by_factor.py analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv 4 normalized_count,avg_count_per_number_of_barcodes,count 1 analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv

# python pyscripts/calculate_ratio_between_other_results.py analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv LLC_2,nMuMG,MEF normalized_count,avg_count_per_number_of_barcodes,count analysis_results/LUNG_CANCER/LET-1/bio_1/comparison_between_other_cells.csv
# python pyscripts/calculate_ratio_between_other_results.py analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv LET-1,nMuMG,MEF normalized_count,avg_count_per_number_of_barcodes,count analysis_results/LUNG_CANCER/LLC_2/bio_1/comparison_between_other_cells.csv
# python pyscripts/calculate_ratio_between_other_results.py analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv LET-1,LLC_2,MEF normalized_count,avg_count_per_number_of_barcodes,count analysis_results/LUNG_CANCER/nMuMG/bio_1/comparison_between_other_cells.csv
# python pyscripts/calculate_ratio_between_other_results.py analysis_results/LUNG_CANCER/MEF/bio_1/summarized_info_of_unique_17_count.csv analysis_results/LUNG_CANCER/LET-1/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/LLC_2/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/LUNG_CANCER/nMuMG/bio_1/summarized_info_of_unique_17_count.csv LET-1,LLC_2,nMuMG normalized_count,avg_count_per_number_of_barcodes,count analysis_results/LUNG_CANCER/MEF/bio_1/comparison_between_other_cells.csv

# python pyscripts/sort_df_by_column.py analysis_results/LUNG_CANCER/LET-1/bio_1/comparison_between_other_cells.csv avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/LET-1/bio_1/comparison_between_other_cells.csv
# python pyscripts/sort_df_by_column.py analysis_results/LUNG_CANCER/LLC_2/bio_1/comparison_between_other_cells.csv avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/LLC_2/bio_1/comparison_between_other_cells.csv
# python pyscripts/sort_df_by_column.py analysis_results/LUNG_CANCER/nMuMG/bio_1/comparison_between_other_cells.csv avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/nMuMG/bio_1/comparison_between_other_cells.csv
# python pyscripts/sort_df_by_column.py analysis_results/LUNG_CANCER/MEF/bio_1/comparison_between_other_cells.csv avg_count_per_number_of_barcodes False analysis_results/LUNG_CANCER/MEF/bio_1/comparison_between_other_cells.csv






# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MDA231/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MDA231/bio_1/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MDA231/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MDA231 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MDA231/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MDA231/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MDA231/bio_2/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MDA231/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MDA231/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MDA231/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MDA231/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/BT474/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/BT474/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/BT474/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/BT474/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 BT474 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/BT474/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/BT474/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/BT474/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/BT474/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/BT474/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/BT474/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/BT474/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/BT474/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/CCD841/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/CCD841/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/CCD841/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/CCD841/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 CCD841 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/CCD841/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/CCD841/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/CCD841/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/CCD841/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/CCD841/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/CCD841/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/CCD841/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/CCD841/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/Colo320DM/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/Colo320DM/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/Colo320DM/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/Colo320DM/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 Colo320DM bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/Colo320DM/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/Colo320DM/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/Colo320DM/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/Colo320DM/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/Colo320DM/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/Colo320DM/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/Colo320DM/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/Colo320DM/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HCT116/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HCT116/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HCT116/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HCT116/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HCT116 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HCT116/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HCT116/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HCT116/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HCT116/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HCT116/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HCT116/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HCT116/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HCT116/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HDFa/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HDFa/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HDFa/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HDFa/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HDFa bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HDFa/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HDFa/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HDFa/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HDFa/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HDFa/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HDFa/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HDFa/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HDFa/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HEK/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HEK/bio_1/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HEK/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HEK bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HEK/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HEK/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HEK/bio_2/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HEK/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HEK/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HEK/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HEK/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HS-578T/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HS-578T/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HS-578T/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HS-578T/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HS-578T bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HS-578T/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HS-578T/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HS-578T/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HS-578T/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HS-578T/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HS-578T/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HS-578T/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HS-578T/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HT29/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HT29/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HT29/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HT29/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 HT29 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/HT29/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HT29/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HT29/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HT29/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HT29/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/HT29/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/HT29/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/HT29/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF7/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF7/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF7/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF7/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF7 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF7/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF7/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF7/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF7/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF7/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF7/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF7/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF7/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF10/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF10/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF10/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF10/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 MCF10 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/MCF10/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF10/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF10/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF10/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF10/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/MCF10/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/MCF10/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/MCF10/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/NL20/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/NL20/bio_1/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/NL20/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 NL20 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/NL20/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/NL20/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/NL20/bio_2/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/NL20/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/NL20/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/NL20/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/NL20/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW480/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW480/bio_1/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW480/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW480 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW480/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW480/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW480/bio_2/tech_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW480/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW480/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW480/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW480/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW620/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW620/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW620/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW620/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 SW620 bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/SW620/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW620/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW620/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW620/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW620/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/SW620/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/SW620/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/SW620/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_1/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_1/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_1/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/T47D/bio_1/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/T47D/bio_1/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/T47D/bio_1/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/T47D/bio_1/summarized_info_of_unique_17_count.csv

# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_2/tech_1/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_2/tech_2/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# ./analyse_replicate.sh analysis_results NIR_748 T47D bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output/NIR_748/T47D/bio_2/tech_3/paired.csv ./pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/C1_lib_data.csv
# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/T47D/bio_2/tech_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/T47D/bio_2/tech_2/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/T47D/bio_2/tech_3/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/T47D/bio_2/summarized_info_of_unique_17_count.csv

# python pyscripts/sum_unique_17_columns.py analysis_results/NIR_748/T47D/bio_1/summarized_info_of_unique_17_count.csv,analysis_results/NIR_748/T47D/bio_2/summarized_info_of_unique_17_count.csv count,avg_count_per_number_of_barcodes,unnormalized_count count False analysis_results/NIR_748/T47D/summarized_info_of_unique_17_count.csv


#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_A s_A_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_A/s_A_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_B s_B_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_B/s_B_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_C s_C_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_C/s_C_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_A k_A_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_A/k_A_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_B k_B_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_B/k_B_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_C k_C_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_C/k_C_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_A s_A_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_A/s_A_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_B s_B_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_B/s_B_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 s bio_C s_C_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/s/bio_C/s_C_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_A k_A_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_A/k_A_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_B k_B_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_B/k_B_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 k bio_C k_C_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/k/bio_C/k_C_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv

#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 viralA "" viral_A_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/viralA/viral_A_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 viralB "" viral_B_PCR1 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/viralB/viral_B_PCR1/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 viralA "" viral_A_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/viralA/viral_A_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv
#./analyse_replicate.sh /cs/icore/tzlil.yair/results/analyse_counts_ALLA/ ALAA_787 viralB "" viral_A_PCR2 /cs/icore/tzlil.yair/results/output_ALAA_run787/ALAA_787/viralB/viral_B_PCR2/paired.csv pyscripts /cs/icore/tzlil.yair/resources/D11_lib_data.csv

#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_A s_A_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_A/s_A_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_B s_B_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_B/s_B_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_C s_C_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_C/s_C_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_A k_A_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_A/k_A_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_B k_B_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_B/k_B_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_C k_C_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_C/k_C_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_A s_A_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_A/s_A_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_B s_B_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_B/s_B_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 s bio_C s_C_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/s/bio_C/s_C_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_A k_A_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_A/k_A_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_B k_B_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_B/k_B_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 k bio_C k_C_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/k/bio_C/k_C_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv

#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 viralA "" viral_A_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/viralA/viral_A_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 viralB "" viral_B_PCR1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/viralB/viral_B_PCR1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 viralA "" viral_A_PCR2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/viralA/viral_A_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv
#./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/Amir_Eden/analyse_counts_ALLA/ ALAA_787 viralB "" viral_A_PCR2 /sci/labs/lior#.nissim/tzlil.yair/SPECS/results/Amir_Eden/output_ALAA_787/ALAA_787/viralB/viral_B_PCR2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/D11_lib_data.csv

./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C20 "" C20_sample_1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C20/C20_sample_1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C20_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C20 "" C20_sample_2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C20/C20_sample_2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C20_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C20 "" C20_sample_3 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C20/C20_sample_3/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C20_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C30 "" C30_dilute1_1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C30/C30_dilute1_1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C30_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C30 "" C30_dilute1_2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C30/C30_dilute1_2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C30_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C30 "" C30_dilute1_3 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C30/C30_dilute1_3/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C30_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C30 "" C30_dilute2_1 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C30/C30_dilute2_1/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C30_lib_data.csv
./analyse_replicate.sh /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/analyse_counts_CHAJA/ CHAJA_795 C30 "" C30_dilute2_2 /sci/labs/lior.nissim/tzlil.yair/SPECS/results/C20_30_run795/output_CHAJA_795/CHAJA_795/C30/C30_dilute2_2/paired.csv pyscripts /sci/labs/lior.nissim/tzlil.yair/SPECS/resources/C30_lib_data.csv

