#!/bin/bash

########################################################################### HEK293T ##########################################################################################

./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_2/clipped_HEK293T_2_rep1.fastq results_2 HEK293T 2 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_2/clipped_HEK293T_2_rep2.fastq results_2 HEK293T 2 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_2/clipped_HEK293T_2_rep3.fastq results_2 HEK293T 2 3 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_3/clipped_HEK293T_3_rep1.fastq results_2 HEK293T 3 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_3/clipped_HEK293T_3_rep2.fastq results_2 HEK293T 3 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/HEK293T/HEK293T_3/clipped_HEK293T_3_rep3.fastq results_2 HEK293T 3 3 100 3

python3 normalize_sum_by_reads.py results_2/HEK293T/bio_2/unique/tech_1/all/by_promoter/unique_HEK293T_bio_2_tech_1_all.csv,results_2/HEK293T/bio_2/unique/tech_2/all/by_promoter/unique_HEK293T_bio_2_tech_2_all.csv,results_2/HEK293T/bio_2/unique/tech_3/all/by_promoter/unique_HEK293T_bio_2_tech_3_all.csv,results_2/HEK293T/bio_3/unique/tech_1/all/by_promoter/unique_HEK293T_bio_3_tech_1_all.csv,results_2/HEK293T/bio_3/unique/tech_2/all/by_promoter/unique_HEK293T_bio_3_tech_2_all.csv,results_2/HEK293T/bio_3/unique/tech_3/all/by_promoter/unique_HEK293T_bio_3_tech_3_all.csv results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_1_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_2_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_3_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_1_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_2_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_3_normalized.csv False

python3 sum_promoters_counts_results.py results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_1_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_2_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_2_tech_3_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_1_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_2_normalized.csv,results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_bio_3_tech_3_normalized.csv ./results_2/HEK293T/analys_bio_2_and_bio_3_all_tech/HEK293T_sum.csv


########################################################################### MEF ##########################################################################################

./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_2/clipped_MEF_2_rep1.fastq results_2 MEF 2 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_2/clipped_MEF_2_rep2.fastq results_2 MEF 2 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_2/clipped_MEF_2_rep3.fastq results_2 MEF 2 3 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_3/clipped_MEF_3_rep1.fastq results_2 MEF 3 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_3/clipped_MEF_3_rep2.fastq results_2 MEF 3 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/MEF/MEF_3/clipped_MEF_3_rep3.fastq results_2 MEF 3 3 100 3

python3 normalize_sum_by_reads.py results_2/MEF/bio_2/unique/tech_1/all/by_promoter/unique_MEF_bio_2_tech_1_all.csv,results_2/MEF/bio_2/unique/tech_2/all/by_promoter/unique_MEF_bio_2_tech_2_all.csv,results_2/MEF/bio_2/unique/tech_3/all/by_promoter/unique_MEF_bio_2_tech_3_all.csv,results_2/MEF/bio_3/unique/tech_1/all/by_promoter/unique_MEF_bio_3_tech_1_all.csv,results_2/MEF/bio_3/unique/tech_2/all/by_promoter/unique_MEF_bio_3_tech_2_all.csv,results_2/MEF/bio_3/unique/tech_3/all/by_promoter/unique_MEF_bio_3_tech_3_all.csv results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_1_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_2_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_3_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_1_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_2_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_3_normalized.csv False

python3 sum_promoters_counts_results.py results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_1_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_2_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_2_tech_3_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_1_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_2_normalized.csv,results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_bio_3_tech_3_normalized.csv ./results_2/MEF/analys_bio_2_and_bio_3_all_tech/MEF_sum.csv

########################################################################### ESC ##########################################################################################

./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_2/clipped_ESC_2_rep1.fastq results_2 ESC 2 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_2/clipped_ESC_2_rep2.fastq results_2 ESC 2 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_2/clipped_ESC_2_rep3.fastq results_2 ESC 2 3 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_3/clipped_ESC_3_rep1.fastq results_2 ESC 3 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_3/clipped_ESC_3_rep2.fastq results_2 ESC 3 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/ESC/ESC_3/clipped_ESC_3_rep3.fastq results_2 ESC 3 3 100 3

python3 normalize_sum_by_reads.py results_2/ESC/bio_2/unique/tech_1/all/by_promoter/unique_ESC_bio_2_tech_1_all.csv,results_2/ESC/bio_2/unique/tech_2/all/by_promoter/unique_ESC_bio_2_tech_2_all.csv,results_2/ESC/bio_2/unique/tech_3/all/by_promoter/unique_ESC_bio_2_tech_3_all.csv,results_2/ESC/bio_3/unique/tech_1/all/by_promoter/unique_ESC_bio_3_tech_1_all.csv,results_2/ESC/bio_3/unique/tech_2/all/by_promoter/unique_ESC_bio_3_tech_2_all.csv,results_2/ESC/bio_3/unique/tech_3/all/by_promoter/unique_ESC_bio_3_tech_3_all.csv results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_1_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_2_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_3_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_1_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_2_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_3_normalized.csv False

python3 sum_promoters_counts_results.py results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_1_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_2_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_2_tech_3_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_1_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_2_normalized.csv,results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_bio_3_tech_3_normalized.csv ./results_2/ESC/analys_bio_2_and_bio_3_all_tech/ESC_sum.csv

########################################################################### XEN ##########################################################################################

./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_2/clipped_XEN_2_rep1.fastq results_2 XEN 2 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_2/clipped_XEN_2_rep2.fastq results_2 XEN 2 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_2/clipped_XEN_2_rep3.fastq results_2 XEN 2 3 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_3/clipped_XEN_3_rep1.fastq results_2 XEN 3 1 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_3/clipped_XEN_3_rep2.fastq results_2 XEN 3 2 100 3
./analys_replica.sh ../scripts/library_preparation/barcodes/asdasd_PAIRED.csv ../RNA-seq/XEN/XEN_3/clipped_XEN_3_rep3.fastq results_2 XEN 3 3 100 3

python3 normalize_sum_by_reads.py results_2/XEN/bio_2/unique/tech_1/all/by_promoter/unique_XEN_bio_2_tech_1_all.csv,results_2/XEN/bio_2/unique/tech_2/all/by_promoter/unique_XEN_bio_2_tech_2_all.csv,results_2/XEN/bio_2/unique/tech_3/all/by_promoter/unique_XEN_bio_2_tech_3_all.csv,results_2/XEN/bio_3/unique/tech_1/all/by_promoter/unique_XEN_bio_3_tech_1_all.csv,results_2/XEN/bio_3/unique/tech_2/all/by_promoter/unique_XEN_bio_3_tech_2_all.csv,results_2/XEN/bio_3/unique/tech_3/all/by_promoter/unique_XEN_bio_3_tech_3_all.csv results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_1_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_2_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_3_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_1_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_2_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_3_normalized.csv False

python3 sum_promoters_counts_results.py results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_1_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_2_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_2_tech_3_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_1_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_2_normalized.csv,results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_bio_3_tech_3_normalized.csv ./results_2/XEN/analys_bio_2_and_bio_3_all_tech/XEN_sum.csv