#!/bin/bash

# ./C1_lib_construction.sh NIR_748 D11 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_D11A_S32_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748 D11 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_D11B_S64_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/D11/bio_1/tech_1/paired.csv,output/NIR_748/D11/bio_1/tech_2/paired.csv output/NIR_748/D11/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/D11/bio_1/paired_combined.csv output/NIR_748/D11/bio_1/distinct_paired.csv output/NIR_748/D11/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748 D7 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_D17A_S31_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748 D7 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_D17B_S63_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/D7/bio_1/tech_1/paired.csv,output/NIR_748/D7/bio_1/tech_2/paired.csv output/NIR_748/D7/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/D7/bio_1/paired_combined.csv output/NIR_748/D7/bio_1/distinct_paired.csv output/NIR_748/D7/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HEK/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A1_S1_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HEK/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B1_S33_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HEK/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C1_S65_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HEK/bio_1/tech_1/paired.csv,output/NIR_748/HEK/bio_1/tech_2/paired.csv,output/NIR_748/HEK/bio_1/tech_3/paired.csv output/NIR_748/HEK/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HEK/bio_1/paired_combined.csv output/NIR_748/HEK/bio_1/distinct_paired.csv output/NIR_748/HEK/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HEK/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A2_S2_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HEK/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B2_S34_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HEK/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C2_S66_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HEK/bio_2/tech_1/paired.csv,output/NIR_748/HEK/bio_2/tech_2/paired.csv,output/NIR_748/HEK/bio_2/tech_3/paired.csv output/NIR_748/HEK/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HEK/bio_2/paired_combined.csv output/NIR_748/HEK/bio_2/distinct_paired.csv output/NIR_748/HEK/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MDA231/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A4_S3_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MDA231/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B4_S35_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MDA231/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C4_S67_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MDA231/bio_1/tech_1/paired.csv,output/NIR_748/MDA231/bio_1/tech_2/paired.csv,output/NIR_748/MDA231/bio_1/tech_3/paired.csv output/NIR_748/MDA231/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MDA231/bio_1/paired_combined.csv output/NIR_748/MDA231/bio_1/distinct_paired.csv output/NIR_748/MDA231/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MDA231/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A5_S4_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MDA231/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B5_S36_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MDA231/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C5_S68_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MDA231/bio_2/tech_1/paired.csv,output/NIR_748/MDA231/bio_2/tech_2/paired.csv,output/NIR_748/MDA231/bio_2/tech_3/paired.csv output/NIR_748/MDA231/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MDA231/bio_2/paired_combined.csv output/NIR_748/MDA231/bio_2/distinct_paired.csv output/NIR_748/MDA231/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/SW620/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A7_S5_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW620/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B7_S37_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW620/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C7_S69_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/SW620/bio_1/tech_1/paired.csv,output/NIR_748/SW620/bio_1/tech_2/paired.csv,output/NIR_748/SW620/bio_1/tech_3/paired.csv output/NIR_748/SW620/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/SW620/bio_1/paired_combined.csv output/NIR_748/SW620/bio_1/distinct_paired.csv output/NIR_748/SW620/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/SW620/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A8_S6_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW620/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B8_S38_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW620/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C8_S70_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/SW620/bio_2/tech_1/paired.csv,output/NIR_748/SW620/bio_2/tech_2/paired.csv,output/NIR_748/SW620/bio_2/tech_3/paired.csv output/NIR_748/SW620/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/SW620/bio_2/paired_combined.csv output/NIR_748/SW620/bio_2/distinct_paired.csv output/NIR_748/SW620/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/SW480/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A10_S7_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW480/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B10_S39_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW480/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C10_S71_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/SW480/bio_1/tech_1/paired.csv,output/NIR_748/SW480/bio_1/tech_2/paired.csv,output/NIR_748/SW480/bio_1/tech_3/paired.csv output/NIR_748/SW480/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/SW480/bio_1/paired_combined.csv output/NIR_748/SW480/bio_1/distinct_paired.csv output/NIR_748/SW480/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/SW480/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A11_S8_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW480/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B11_S40_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/SW480/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C11_S72_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/SW480/bio_2/tech_1/paired.csv,output/NIR_748/SW480/bio_2/tech_2/paired.csv,output/NIR_748/SW480/bio_2/tech_3/paired.csv output/NIR_748/SW480/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/SW480/bio_2/paired_combined.csv output/NIR_748/SW480/bio_2/distinct_paired.csv output/NIR_748/SW480/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HS-578T/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A13_S9_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HS-578T/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B13_S41_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HS-578T/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C13_S73_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HS-578T/bio_1/tech_1/paired.csv,output/NIR_748/HS-578T/bio_1/tech_2/paired.csv,output/NIR_748/HS-578T/bio_1/tech_3/paired.csv output/NIR_748/HS-578T/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HS-578T/bio_1/paired_combined.csv output/NIR_748/HS-578T/bio_1/distinct_paired.csv output/NIR_748/HS-578T/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HS-578T/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A14_S10_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HS-578T/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B14_S42_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HS-578T/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C14_S74_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HS-578T/bio_2/tech_1/paired.csv,output/NIR_748/HS-578T/bio_2/tech_2/paired.csv,output/NIR_748/HS-578T/bio_2/tech_3/paired.csv output/NIR_748/HS-578T/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HS-578T/bio_2/paired_combined.csv output/NIR_748/HS-578T/bio_2/distinct_paired.csv output/NIR_748/HS-578T/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MCF10/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A16_S11_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF10/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B16_S43_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF10/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C16_S75_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MCF10/bio_1/tech_1/paired.csv,output/NIR_748/MCF10/bio_1/tech_2/paired.csv,output/NIR_748/MCF10/bio_1/tech_3/paired.csv output/NIR_748/MCF10/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MCF10/bio_1/paired_combined.csv output/NIR_748/MCF10/bio_1/distinct_paired.csv output/NIR_748/MCF10/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MCF10/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A17_S12_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF10/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B17_S44_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF10/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C17_S76_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MCF10/bio_2/tech_1/paired.csv,output/NIR_748/MCF10/bio_2/tech_2/paired.csv,output/NIR_748/MCF10/bio_2/tech_3/paired.csv output/NIR_748/MCF10/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MCF10/bio_2/paired_combined.csv output/NIR_748/MCF10/bio_2/distinct_paired.csv output/NIR_748/MCF10/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HT29/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A19_S13_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HT29/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B19_S45_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HT29/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C19_S77_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HT29/bio_1/tech_1/paired.csv,output/NIR_748/HT29/bio_1/tech_2/paired.csv,output/NIR_748/HT29/bio_1/tech_3/paired.csv output/NIR_748/HT29/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HT29/bio_1/paired_combined.csv output/NIR_748/HT29/bio_1/distinct_paired.csv output/NIR_748/HT29/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HT29/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A20_S14_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HT29/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B20_S46_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HT29/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C20_S78_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HT29/bio_2/tech_1/paired.csv,output/NIR_748/HT29/bio_2/tech_2/paired.csv,output/NIR_748/HT29/bio_2/tech_3/paired.csv output/NIR_748/HT29/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HT29/bio_2/paired_combined.csv output/NIR_748/HT29/bio_2/distinct_paired.csv output/NIR_748/HT29/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HCT116/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A22_S15_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HCT116/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B22_S47_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HCT116/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C22_S79_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HCT116/bio_1/tech_1/paired.csv,output/NIR_748/HCT116/bio_1/tech_2/paired.csv,output/NIR_748/HCT116/bio_1/tech_3/paired.csv output/NIR_748/HCT116/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HCT116/bio_1/paired_combined.csv output/NIR_748/HCT116/bio_1/distinct_paired.csv output/NIR_748/HCT116/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HCT116/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A23_S16_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HCT116/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B23_S48_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HCT116/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C23_S80_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HCT116/bio_2/tech_1/paired.csv,output/NIR_748/HCT116/bio_2/tech_2/paired.csv,output/NIR_748/HCT116/bio_2/tech_3/paired.csv output/NIR_748/HCT116/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HCT116/bio_2/paired_combined.csv output/NIR_748/HCT116/bio_2/distinct_paired.csv output/NIR_748/HCT116/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A25_S17_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B25_S49_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C25_S81_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/Colo320DM/bio_1/tech_1/paired.csv,output/NIR_748/Colo320DM/bio_1/tech_2/paired.csv,output/NIR_748/Colo320DM/bio_1/tech_3/paired.csv output/NIR_748/Colo320DM/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/Colo320DM/bio_1/paired_combined.csv output/NIR_748/Colo320DM/bio_1/distinct_paired.csv output/NIR_748/Colo320DM/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A26_S18_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B26_S50_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/Colo320DM/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C26_S82_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/Colo320DM/bio_2/tech_1/paired.csv,output/NIR_748/Colo320DM/bio_2/tech_2/paired.csv,output/NIR_748/Colo320DM/bio_2/tech_3/paired.csv output/NIR_748/Colo320DM/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/Colo320DM/bio_2/paired_combined.csv output/NIR_748/Colo320DM/bio_2/distinct_paired.csv output/NIR_748/Colo320DM/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/T47D/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A28_S19_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/T47D/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B28_S51_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/T47D/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C28_S83_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/T47D/bio_1/tech_1/paired.csv,output/NIR_748/T47D/bio_1/tech_2/paired.csv,output/NIR_748/T47D/bio_1/tech_3/paired.csv output/NIR_748/T47D/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/T47D/bio_1/paired_combined.csv output/NIR_748/T47D/bio_1/distinct_paired.csv output/NIR_748/T47D/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/T47D/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A29_S20_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/T47D/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B29_S52_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/T47D/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C29_S84_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/T47D/bio_2/tech_1/paired.csv,output/NIR_748/T47D/bio_2/tech_2/paired.csv,output/NIR_748/T47D/bio_2/tech_3/paired.csv output/NIR_748/T47D/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/T47D/bio_2/paired_combined.csv output/NIR_748/T47D/bio_2/distinct_paired.csv output/NIR_748/T47D/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MCF7/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A31_S21_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF7/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B31_S53_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF7/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C31_S85_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MCF7/bio_1/tech_1/paired.csv,output/NIR_748/MCF7/bio_1/tech_2/paired.csv,output/NIR_748/MCF7/bio_1/tech_3/paired.csv output/NIR_748/MCF7/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MCF7/bio_1/paired_combined.csv output/NIR_748/MCF7/bio_1/distinct_paired.csv output/NIR_748/MCF7/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/MCF7/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A32_S22_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF7/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B32_S54_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/MCF7/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C32_S86_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/MCF7/bio_2/tech_1/paired.csv,output/NIR_748/MCF7/bio_2/tech_2/paired.csv,output/NIR_748/MCF7/bio_2/tech_3/paired.csv output/NIR_748/MCF7/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/MCF7/bio_2/paired_combined.csv output/NIR_748/MCF7/bio_2/distinct_paired.csv output/NIR_748/MCF7/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/BT474/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A34_S23_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/BT474/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B34_S55_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/BT474/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C34_S87_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/BT474/bio_1/tech_1/paired.csv,output/NIR_748/BT474/bio_1/tech_2/paired.csv,output/NIR_748/BT474/bio_1/tech_3/paired.csv output/NIR_748/BT474/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/BT474/bio_1/paired_combined.csv output/NIR_748/BT474/bio_1/distinct_paired.csv output/NIR_748/BT474/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/BT474/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A35_S24_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/BT474/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B35_S56_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/BT474/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C35_S88_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/BT474/bio_2/tech_1/paired.csv,output/NIR_748/BT474/bio_2/tech_2/paired.csv,output/NIR_748/BT474/bio_2/tech_3/paired.csv output/NIR_748/BT474/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/BT474/bio_2/paired_combined.csv output/NIR_748/BT474/bio_2/distinct_paired.csv output/NIR_748/BT474/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/CCD841/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A37_S25_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/CCD841/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B37_S57_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/CCD841/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C37_S89_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/CCD841/bio_1/tech_1/paired.csv,output/NIR_748/CCD841/bio_1/tech_2/paired.csv,output/NIR_748/CCD841/bio_1/tech_3/paired.csv output/NIR_748/CCD841/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/CCD841/bio_1/paired_combined.csv output/NIR_748/CCD841/bio_1/distinct_paired.csv output/NIR_748/CCD841/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/CCD841/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A38_S26_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/CCD841/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B38_S58_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/CCD841/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C38_S90_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/CCD841/bio_2/tech_1/paired.csv,output/NIR_748/CCD841/bio_2/tech_2/paired.csv,output/NIR_748/CCD841/bio_2/tech_3/paired.csv output/NIR_748/CCD841/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/CCD841/bio_2/paired_combined.csv output/NIR_748/CCD841/bio_2/distinct_paired.csv output/NIR_748/CCD841/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/NL20/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A40_S27_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/NL20/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B40_S59_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/NL20/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C40_S91_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/NL20/bio_1/tech_1/paired.csv,output/NIR_748/NL20/bio_1/tech_2/paired.csv,output/NIR_748/NL20/bio_1/tech_3/paired.csv output/NIR_748/NL20/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/NL20/bio_1/paired_combined.csv output/NIR_748/NL20/bio_1/distinct_paired.csv output/NIR_748/NL20/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/NL20/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A41_S28_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/NL20/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B41_S60_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/NL20/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C41_S92_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/NL20/bio_2/tech_1/paired.csv,output/NIR_748/NL20/bio_2/tech_2/paired.csv,output/NIR_748/NL20/bio_2/tech_3/paired.csv output/NIR_748/NL20/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/NL20/bio_2/paired_combined.csv output/NIR_748/NL20/bio_2/distinct_paired.csv output/NIR_748/NL20/bio_2/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HDFa/bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A43_S29_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HDFa/bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B43_S61_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HDFa/bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C43_S93_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HDFa/bio_1/tech_1/paired.csv,output/NIR_748/HDFa/bio_1/tech_2/paired.csv,output/NIR_748/HDFa/bio_1/tech_3/paired.csv output/NIR_748/HDFa/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HDFa/bio_1/paired_combined.csv output/NIR_748/HDFa/bio_1/distinct_paired.csv output/NIR_748/HDFa/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh NIR_748/HDFa/bio_2 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_A44_S30_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HDFa/bio_2 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_B44_S62_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh NIR_748/HDFa/bio_2 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Nir_run748/NIR_C44_S94_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/NIR_748/HDFa/bio_2/tech_1/paired.csv,output/NIR_748/HDFa/bio_2/tech_2/paired.csv,output/NIR_748/HDFa/bio_2/tech_3/paired.csv output/NIR_748/HDFa/bio_2/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/NIR_748/HDFa/bio_2/paired_combined.csv output/NIR_748/HDFa/bio_2/distinct_paired.csv output/NIR_748/HDFa/bio_2/number_of_BC_per_unique_17.csv




# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_7 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_7_S1_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_8 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_8_S2_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_9 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_9_S3_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_10 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_10_S4_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_11 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_11_S5_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_12 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_12_S6_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LiorWhite Lib bio_1 tech_13 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/LiorWhite_run715/Lior_white_13_S7_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LiorWhite/Lib/bio_1/tech_7/paired.csv,output/LiorWhite/Lib/bio_1/tech_8/paired.csv,output/LiorWhite/Lib/bio_1/tech_9/paired.csv,output/LiorWhite/Lib/bio_1/tech_9/paired.csv,output/LiorWhite/Lib/bio_1/tech_10/paired.csv,output/LiorWhite/Lib/bio_1/tech_11/paired.csv,output/LiorWhite/Lib/bio_1/tech_12/paired.csv,output/LiorWhite/Lib/bio_1/tech_13/paired.csv output/LiorWhite/Lib/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LiorWhite/Lib/bio_1/paired_combined.csv output/LiorWhite/Lib/bio_1/distinct_paired.csv output/LiorWhite/Lib/bio_1/number_of_BC_per_unique_17.csv




# ./C1_lib_construction.sh LUNG_CANCER LLC bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_1_S1_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LLC bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_2_S2_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LLC bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_3_S3_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LLC bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_4_S4_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LUNG_CANCER/LLC/bio_1/tech_1/paired.csv,output/LUNG_CANCER/LLC/bio_1/tech_2/paired.csv,output/LUNG_CANCER/LLC/bio_1/tech_3/paired.csv,output/LUNG_CANCER/LLC/bio_1/tech_4/paired.csv output/LUNG_CANCER/LLC/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LUNG_CANCER/LLC/bio_1/paired_combined.csv output/LUNG_CANCER/LLC/bio_1/distinct_paired.csv output/LUNG_CANCER/LLC/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh LUNG_CANCER LET-1 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_5_S5_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LET-1 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_6_S6_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LET-1 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_7_S7_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LET-1 bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_8_S8_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LUNG_CANCER/LET-1/bio_1/tech_1/paired.csv,output/LUNG_CANCER/LET-1/bio_1/tech_2/paired.csv,output/LUNG_CANCER/LET-1/bio_1/tech_3/paired.csv,output/LUNG_CANCER/LET-1/bio_1/tech_4/paired.csv output/LUNG_CANCER/LET-1/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LUNG_CANCER/LET-1/bio_1/paired_combined.csv output/LUNG_CANCER/LET-1/bio_1/distinct_paired.csv output/LUNG_CANCER/LET-1/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh LUNG_CANCER MEF bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_9_S9_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER MEF bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_10_S10_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER MEF bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_11_S11_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER MEF bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_12_S12_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LUNG_CANCER/MEF/bio_1/tech_1/paired.csv,output/LUNG_CANCER/MEF/bio_1/tech_2/paired.csv,output/LUNG_CANCER/MEF/bio_1/tech_3/paired.csv,output/LUNG_CANCER/MEF/bio_1/tech_4/paired.csv output/LUNG_CANCER/MEF/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LUNG_CANCER/MEF/bio_1/paired_combined.csv output/LUNG_CANCER/MEF/bio_1/distinct_paired.csv output/LUNG_CANCER/MEF/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh LUNG_CANCER nMuMG bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_13_S13_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER nMuMG bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_14_S14_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER nMuMG bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_15_S15_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER nMuMG bio_1 tech_4 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_16_S16_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LUNG_CANCER/nMuMG/bio_1/tech_1/paired.csv,output/LUNG_CANCER/nMuMG/bio_1/tech_2/paired.csv,output/LUNG_CANCER/nMuMG/bio_1/tech_3/paired.csv,output/LUNG_CANCER/nMuMG/bio_1/tech_4/paired.csv output/LUNG_CANCER/nMuMG/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LUNG_CANCER/nMuMG/bio_1/paired_combined.csv output/LUNG_CANCER/nMuMG/bio_1/distinct_paired.csv output/LUNG_CANCER/nMuMG/bio_1/number_of_BC_per_unique_17.csv

# ./C1_lib_construction.sh LUNG_CANCER LLC_2 bio_1 tech_1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_17_S17_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LLC_2 bio_1 tech_2 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_18_S18_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# ./C1_lib_construction.sh LUNG_CANCER LLC_2 bio_1 tech_3 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/Lior_run728/LIOR_19_S19_R1_001.fastq /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/pyscripts /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/bowtie2_lib_C1/C1 /Users/bzaruk/Documents/Projects/bzaruk/SPECS/resources/define_local_exec_paths.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/C1/lib_construction/output
# python ../pyscripts/append_results.py output/LUNG_CANCER/LLC_2/bio_1/tech_1/paired.csv,output/LUNG_CANCER/LLC_2/bio_1/tech_2/paired.csv,output/LUNG_CANCER/LLC_2/bio_1/tech_3/paired.csv output/LUNG_CANCER/LLC_2/bio_1/paired_combined.csv
# python pyscripts/extract_distinct_pairing_and_number_of_barcodes_per_unique_17.py output/LUNG_CANCER/LLC_2/bio_1/paired_combined.csv output/LUNG_CANCER/LLC_2/bio_1/distinct_paired.csv output/LUNG_CANCER/LLC_2/bio_1/number_of_BC_per_unique_17.csv


#./C1_lib_construction.sh ALAA_787 s bio_A s_A_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_1_S14_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 s bio_B s_B_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_2_S15_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 s bio_C s_C_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_3_S16_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_A k_A_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_4_S17_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_B k_B_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_5_S18_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_C k_C_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_6_S19_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 viralA "" viral_A_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_7_S20_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 viralB "" viral_B_PCR1 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_8_S21_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 s bio_A s_A_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_9_S22_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 s bio_B s_B_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_10_S23_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 s bio_C s_C_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_11_S24_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_A k_A_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_12_S25_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_B k_B_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_13_S26_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 k bio_C k_C_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_14_S27_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 viralA "" viral_A_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_15_S28_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
#./C1_lib_construction.sh ALAA_787 viralB "" viral_B_PCR2 /cs/icore/tzlil.yair/Downloads/ALAA_run787/ALAA_16_S29_R1_001.fastq pyscripts bowtie2_lib_C1/C1 "" /cs/icore/tzlil.yair/results/output_ALAA_run787
