#!/bin/bash

./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A43/results/clipped_A43.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B43/results/clipped_B43.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C43/results/clipped_C43.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A44/results/clipped_A44.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B44/results/clipped_B44.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C44/results/clipped_C44.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A46/results/clipped_A46.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B46/results/clipped_B46.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C46/results/clipped_C46.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A47/results/clipped_A47.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B47/results/clipped_B47.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C47/results/clipped_C47.fastq NIR_BREAST_COLORECTAL_avg SW480_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A49/results/clipped_A49.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B49/results/clipped_B49.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C49/results/clipped_C49.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A50/results/clipped_A50.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B50/results/clipped_B50.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C50/results/clipped_C50.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A52/results/clipped_A52.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B52/results/clipped_B52.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C52/results/clipped_C52.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A53/results/clipped_A53.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B53/results/clipped_B53.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C53/results/clipped_C53.fastq NIR_BREAST_COLORECTAL_avg HDFa_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A55/results/clipped_A55.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B55/results/clipped_B55.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C55/results/clipped_C55.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A56/results/clipped_A56.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B56/results/clipped_B56.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C56/results/clipped_C56.fastq NIR_BREAST_COLORECTAL_avg NL20_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A68/results/clipped_A68.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B68/results/clipped_B68.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C68/results/clipped_C68.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A69/results/clipped_A69.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B69/results/clipped_B69.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C69/results/clipped_C69.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A71/results/clipped_A71.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B71/results/clipped_B71.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C71/results/clipped_C71.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A72/results/clipped_A72.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B72/results/clipped_B72.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C72/results/clipped_C72.fastq NIR_BREAST_COLORECTAL_avg SW620_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A77/results/clipped_A77.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B77/results/clipped_B77.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C77/results/clipped_C77.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A78/results/clipped_A78.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B78/results/clipped_B78.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C78/results/clipped_C78.fastq NIR_BREAST_COLORECTAL_avg Colon320DM_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A80/results/clipped_A80.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B80/results/clipped_B80.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C80/results/clipped_C80.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A81/results/clipped_A81.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B81/results/clipped_B81.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C81/results/clipped_C81.fastq NIR_BREAST_COLORECTAL_avg HEK_1_2 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A85/results/clipped_A85.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B85/results/clipped_B85.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C85/results/clipped_C85.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A87/results/clipped_A87.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B87/results/clipped_B87.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C87/results/clipped_C87.fastq NIR_BREAST_COLORECTAL_avg T47D_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A89/results/clipped_A89.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B89/results/clipped_B89.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C89/results/clipped_C89.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A91/results/clipped_A91.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B91/results/clipped_B91.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C91/results/clipped_C91.fastq NIR_BREAST_COLORECTAL_avg HT29_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A93/results/clipped_A93.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B93/results/clipped_B93.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C93/results/clipped_C93.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A95/results/clipped_A95.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B95/results/clipped_B95.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C95/results/clipped_C95.fastq NIR_BREAST_COLORECTAL_avg HCT116_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A97/results/clipped_A97.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B97/results/clipped_B97.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C97/results/clipped_C97.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A99/results/clipped_A99.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B99/results/clipped_B99.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C99/results/clipped_C99.fastq NIR_BREAST_COLORECTAL_avg MCF-10_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A101/results/clipped_A101.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B101/results/clipped_B101.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C101/results/clipped_C101.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A103/results/clipped_A103.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B103/results/clipped_B103.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C103/results/clipped_C103.fastq NIR_BREAST_COLORECTAL_avg MCF-7_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A105/results/clipped_A105.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B105/results/clipped_B105.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C105/results/clipped_C105.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A107/results/clipped_A107.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B107/results/clipped_B107.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C107/results/clipped_C107.fastq NIR_BREAST_COLORECTAL_avg MDA-231_1_4 2 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A115/results/clipped_A115.fastq NIR_BREAST_COLORECTAL_avg HS578T_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B115/results/clipped_B115.fastq NIR_BREAST_COLORECTAL_avg HS578T_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C115/results/clipped_C115.fastq NIR_BREAST_COLORECTAL_avg HS578T_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A117/results/clipped_A117.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 1 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B117/results/clipped_B117.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 1 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C117/results/clipped_C117.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 1 3 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/A119/results/clipped_A119.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 2 1 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/B119/results/clipped_B119.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 2 2 100 3
./analyse_replicate.sh /Users/bzaruk/Documents/Projects/bzaruk/SPECS/lib_construction_process_scripts/output/D7/results/D7_PAIRED.csv /Users/bzaruk/Documents/Projects/bzaruk/SPECS/RNA_seq_preprocess/output/NIR_BREAST_COLORECTAL/C119/results/clipped_C119.fastq NIR_BREAST_COLORECTAL_avg HEK_1_4 2 3 100 3


# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CRYE1/results/clipped_CRYE1.fastq SHARON CRYE 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CRYE2/results/clipped_CRYE2.fastq SHARON CRYE 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CRYE3/results/clipped_CRYE3.fastq SHARON CRYE 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CTL1/results/clipped_CTL1.fastq SHARON CTL 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CTL2/results/clipped_CTL2.fastq SHARON CTL 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/CTL3/results/clipped_CTL3.fastq SHARON CTL 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/LOW_O1/results/clipped_LOW_O1.fastq SHARON LOW 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/LOW_O2/results/clipped_LOW_O2.fastq SHARON LOW 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/LOW_O3/results/clipped_LOW_O3.fastq SHARON LOW 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST110_1/results/clipped_ST110_1.fastq SHARON ST110 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST110_2/results/clipped_ST110_2.fastq SHARON ST110 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST110_3/results/clipped_ST110_3.fastq SHARON ST110 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST11_1/results/clipped_ST11_1.fastq SHARON ST11 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST11_2/results/clipped_ST11_2.fastq SHARON ST11 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/ST11_3/results/clipped_ST11_3.fastq SHARON ST11 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/STARV1/results/clipped_STARV1.fastq SHARON STARV 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/STARV2/results/clipped_STARV2.fastq SHARON STARV 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/STARV3/results/clipped_STARV3.fastq SHARON STARV 1 3 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/TOXIC1/results/clipped_TOXIC1.fastq SHARON TOXIC 1 1 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/TOXIC2/results/clipped_TOXIC2.fastq SHARON TOXIC 1 2 100 3
# ./analyse_replicate.sh ../lib_construction_process_scripts/barcode_promoter_pairing_output/first_library/results/first_library_PAIRED.csv ../RNA_seq_preprocess/output/SHARON/TOXIC3/results/clipped_TOXIC3.fastq SHARON TOXIC 1 3 100 3



# ./D11_lib_construction.sh LUNG_CANCER sample_2 ../resources/Lior_Lung_Cancer/LIOR_2_S2_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_3 ../resources/Lior_Lung_Cancer/LIOR_3_S3_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_4 ../resources/Lior_Lung_Cancer/LIOR_4_S4_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_5 ../resources/Lior_Lung_Cancer/LIOR_5_S5_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_6 ../resources/Lior_Lung_Cancer/LIOR_6_S6_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_7 ../resources/Lior_Lung_Cancer/LIOR_7_S7_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_8 ../resources/Lior_Lung_Cancer/LIOR_8_S8_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_9 ../resources/Lior_Lung_Cancer/LIOR_9_S9_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_10 ../resources/Lior_Lung_Cancer/LIOR_10_S10_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_11 ../resources/Lior_Lung_Cancer/LIOR_11_S11_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_12 ../resources/Lior_Lung_Cancer/LIOR_12_S12_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_13 ../resources/Lior_Lung_Cancer/LIOR_13_S13_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_14 ../resources/Lior_Lung_Cancer/LIOR_14_S14_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_15 ../resources/Lior_Lung_Cancer/LIOR_15_S15_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_16 ../resources/Lior_Lung_Cancer/LIOR_16_S16_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_17 ../resources/Lior_Lung_Cancer/LIOR_17_S17_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_18 ../resources/Lior_Lung_Cancer/LIOR_18_S18_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11
# ./D11_lib_construction.sh LUNG_CANCER sample_19 ../resources/Lior_Lung_Cancer/LIOR_19_S19_R1_001.fastq ../pyscripts ../lib_construction_process_scripts/bowtie2_lib_D11/D11